[workspace]
resolver = "2"
members = ["crates/echo-core", "crates/echo", "crates/xtask", "src-tauri"]

[workspace.package]
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/ddv1982/echo"
rust-version = "1.88"
version = "0.1.0"

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
all = { level = "deny", priority = -1 }
