#!/usr/bin/env python3
"""Generate the Whisper language table for echo-core from upstream whisper.cpp.

Reads the g_lang map in src/whisper.cpp (fetched from ggml-org/whisper.cpp
master by default, or a local checkout via --input) and rewrites
crates/echo-core/src/language_table.rs. Rerun it when upstream adds a
language; the table is checked in so builds need no network.

    python3 scripts/generate-language-table.py [--input /path/to/whisper.cpp] [--check]

--check compares the generated table with the checked-in file and exits 1 on
drift, without writing.
"""

import argparse
import re
import urllib.request
from pathlib import Path

UPSTREAM = "https://raw.githubusercontent.com/ggml-org/whisper.cpp/master/src/whisper.cpp"
DEST = Path(__file__).resolve().parent.parent / "crates/echo-core/src/language_table.rs"

ENTRY = re.compile(r'\{\s*"([a-z]+)",\s*\{\s*(\d+),\s*"([^"]+)",?\s*\}\s*\},')

HEADER = """// Generated by scripts/generate-language-table.py from the g_lang map in
// whisper.cpp's src/whisper.cpp. Do not hand-edit; rerun the generator.
// large-v2 reports 99 languages; large-v3 reports 100. Cantonese (yue, id 99)
// is what v3 added.
"""


def parse_entries(source: str) -> list[tuple[str, int, str]]:
    start = source.index("g_lang = {")
    end = source.index("};", start)
    entries = [
        (code, int(lang_id), name)
        for code, lang_id, name in ENTRY.findall(source[start:end])
    ]
    if len(entries) != 100:
        raise SystemExit(f"expected 100 languages in g_lang, found {len(entries)}")
    ids = sorted(lang_id for _, lang_id, _ in entries)
    if ids != list(range(100)):
        raise SystemExit("g_lang ids are not 0..99 contiguous")
    return entries


def render(entries: list[tuple[str, int, str]]) -> str:
    lines = [HEADER, "pub(crate) static LANGUAGE_TABLE: &[(&str, u16, &str)] = &["]
    for code, lang_id, name in entries:
        lines.append(f'    ("{code}", {lang_id}, "{name}"),')
    lines.append("];\n")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", help="local whisper.cpp source instead of fetching")
    parser.add_argument("--check", action="store_true", help="fail on drift, write nothing")
    args = parser.parse_args()

    if args.input:
        source = Path(args.input).read_text()
    else:
        with urllib.request.urlopen(UPSTREAM, timeout=30) as response:
            source = response.read().decode()

    rendered = render(parse_entries(source))
    if args.check:
        current = DEST.read_text() if DEST.exists() else ""
        if current != rendered:
            raise SystemExit(f"{DEST} is stale; rerun scripts/generate-language-table.py")
        return
    DEST.write_text(rendered)
    print(f"wrote {DEST}")


if __name__ == "__main__":
    main()
