pub mod audio;
mod build_identity;
pub mod hotkey;
pub mod inject;
pub mod install;
pub mod microphone;
pub mod notify;
pub mod rec;
pub mod settings;
pub mod status;
pub mod stt;
pub mod transcribe;
pub mod ui;
pub mod upgrade;
pub mod which;
